name: zEssentials
version: ${version}
main: fr.maxlego08.essentials.ZEssentialsPlugin
folia-supported: true
description: Provides an essential, core set of commands for Bukkit.
website: https://groupez.dev/
author: [ Maxlego08 ]
contributors: [ Louis_Dew, Traqueur, JavaToastDev, Melon-Oof, alwyn974, Mapacheee, NeiiZun, groundbreakingmc ]
depend:
  - zMenu
  - PlaceholderAPI
softdepend:
  - Vault
  - ProtocolLib
  - SuperiorSkyblock2
  - BentoBox
api-version: '1.20'
libraries:
  - 'org.mariadb.jdbc:mariadb-java-client:3.5.6'
